apiVersion: v1
data:
  node-configuration.xml: |-
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="
            http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans.xsd">
        <bean class="org.apache.ignite.configuration.IgniteConfiguration">
            <property name="discoverySpi">
                <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                    <property name="ipFinder">
                        <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder">
                            <property name="namespace" value="ignite"/>
                            <property name="serviceName" value="ignite-service"/>
                        </bean>
                    </property>
                </bean>
            </property>
        </bean>
    </beans>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ignite-config
  namespace: ignite
