apiVersion: v1
kind: Service
metadata:
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.serviceName
  name: ignite-service
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.namespace
  namespace: ignite
  labels:
    app: ignite
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: thinclients
      port: 10800
      targetPort: 10800
      protocol: TCP
  # Optional - remove 'sessionAffinity' property if the cluster
  # and applications are deployed within Kubernetes
  #  sessionAffinity: ClientIP
  selector:
    # Must be equal to the label set for pods.
    app: ignite
status:
  loadBalancer: {}